#language: java
#sudo: false
#script: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#language: java
#os: linux
#
#branches:
#  except:
#    - /.*test$/
#
#env:
#  global:
#    - secure: "HZ7J4B0hSDB2H6ljNXYp7LKgFAA3TUFF22qlSVBiI8Qb3dChwM6t/sNVhQnMKfTREOinpvLOt9rDwHBz1ysPtP+r0iqQyDo5GQDTyTXkFskQFO4myelOamZguJQu+bNTQgKHoF1vbFTysC5mpcInYhcu5veLkgH1PRgNFQcqles="
#    - secure: "CVY1NoFW3e3Hfvgvu2mMC4vaQdmPmyHvuFzqqGlpdH3fdMdqG1xzHi+oXv0gK3tbxB0JNfXXvIiNXpGZ06nGcvQYGIRdRU3armJ3P3zv8KXrhitiv1HS08K4pMzgv9+uVwTdxgC0np5tVWQDvV2MSd424ykZrvR07tm2JWxIybU="
#  matrix:
#    - CUSTOM_JDK="default"
#    - CUSTOM_JDK="oraclejdk8"
#
#matrix:
#  exclude:
#     # On Linux, run with specific JDKs only.
#     - os: linux
#       env: CUSTOM_JDK="default"
#
#before_install:
#    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then jdk_switcher use "$CUSTOM_JDK"; fi
#
#before_script:
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install build-essential automake1.10 libtool; fi
#
#mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#
#after_success:
#  - mvn -P linux64 jacoco:report coveralls:report
#
#after_failure:
#  - cat lmdbjni-linux64/target/surefire-reports/*.txt
#{
#  "language": "java",
##  mvn test
#  "os": "linux",
#  "jdk": "oraclejdk8",
#  "env": "CUSTOM_JDK=\"oraclejdk8\"",
#  "before_install": [
#    "if [ \"$TRAVIS_OS_NAME\" == \"linux\" ]; then jdk_switcher use \"$CUSTOM_JDK\"; fi"
#  ],
#  "before_script": [
#    "if [ \"$TRAVIS_OS_NAME\" == \"linux\" ]; then sudo apt-get install build-essential automake1.10 libtool; fi"
#  ],
#  "after_success": [
#    "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
#  ],
#  "after_failure": [
#    "cat lmdbjni-linux64/target/surefire-reports/*.txt"
#  ],
#  "global_env": "HZ7J4B0hSDB2H6ljNXYp7LKgFAA3TUFF22qlSVBiI8Qb3dChwM6t/sNVhQnMKfTREOinpvLOt9rDwHBz1ysPtP+r0iqQyDo5GQDTyTXkFskQFO4myelOamZguJQu+bNTQgKHoF1vbFTysC5mpcInYhcu5veLkgH1PRgNFQcqles=[secure] CVY1NoFW3e3Hfvgvu2mMC4vaQdmPmyHvuFzqqGlpdH3fdMdqG1xzHi+oXv0gK3tbxB0JNfXXvIiNXpGZ06nGcvQYGIRdRU3armJ3P3zv8KXrhitiv1HS08K4pMzgv9+uVwTdxgC0np5tVWQDvV2MSd424ykZrvR07tm2JWxIybU=[secure]",
#  "group": "stable",
#  "dist": "precise"
#}

#{
#  "language": "java",
#  "script": "mvn test -f ./source/pom.xml",
#  "jdk": "oraclejdk8",
#  "group": "stable",
#  "dist": "precise",
#  "os": "linux"
#}
language: java

sudo: false

env:
  global:
    - secure: "ZUWmLfRxoNhxg6YQDRirZYHcv7OH6EKpgQJpRWoxsF1MMNTlnH7XMkiev3d0J5lppe00gi8Guf90XNGHcfe9X/125cYiMQSjRRt6PkiYL8og8+lip4HDfihuXN2h6BcRrBZ7dm5izeSGVzw0GEg0yyav0oqoqLpyzQaZssjXgDY="

script:
 - mvn -V -e -fae -B clean
  - mvn -V -e -fae -B install
  

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2